### DISCUSSION TITLE
Using Macros in Python Docstrings with Material for MkDocs

### DISCUSSION THREAD

**Discussion by nh916** [fralau/mkdocs-macros-plugin#174] [Q&A]
Hi everyone,

I'm currently working on documenting my Python package using [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), and I'm having a great experience with it so far. 

One of the things I want to achieve is to use custom variables (macros) in my documentation to make it more maintainable. I have successfully used macros in my `.md` files, but I'm facing some challenges when trying to use them in my Python docstrings.

To clarify, in my `.md` files, I'm following the standard approach using macros, and it works like a charm:

```yaml
# mkdocs.yaml
plugins:
  - macros

extra:
  homepage: https://my-website.org
```

```md
<!-- my_file.md -->
[my link]({{ homepage }}/about/)
```

However, when I attempted to load macros from my Python docstrings, it didn't work as expected and it would output `[my link]({{ homepage }}/about/)`

Here's what I tried:

```yaml
# mkdocs.yaml
plugins:
  - macros

extra:
  homepage: https://my-website.org
```

```python
# some_module.py

class MyClass:
    """
    My class documentation.

    [my link]({{ homepage }}/about/)  # This doesn't work as it gets outputted literally as `{{ homepage }}`
    """
    pass
```

Thanks in advance for any assistance or suggestions you can offer!
