### DISCUSSION TITLE
use include_yaml macro to add the nav section does not work

### DISCUSSION THREAD

**Discussion by sdellwig** [fralau/mkdocs-macros-plugin#181] [Q&A]
I wanted to load the navigation from an external file.
I included
```
plugins:
  - macros:
      include_yaml:
        - nav.yml
```
where the file includes the 'nav:' tag.
The file is loaded, because other tags like variables in the extra section were loaded but unfortunately the nav section seems to be ignored. 

Has anyone successfully managed to load the nav from an external file? Do you know why this might not work properly?
