### DISCUSSION TITLE
Problem with include_yaml and template partials

### DISCUSSION THREAD

**Discussion by pvdemael** [fralau/mkdocs-macros-plugin#189] [Ideas]
Just started using MkDocs and discovered this plugin, awesome!

## Use case
I use Material for MkDocs and want to add extra menu items(e.g. an extra Download Now link).

## What works but suboptimal
What I did to make it work:
Added a variable to extra in mkdocs.yml:
```yaml
extra:
  extra_tabs:
    - title: Link 1
      url: https://example1.com
    - title: Link 2
      url: https://example2.com
      icon: .icons/material/information-slab-box-outline.svg
```
Override tabs.html partial and add some code to generate the menu items:
```html
{% if "extra_tabs" in config.extra %}
  <!-- Adds tab on right side of header -->
  <ul class="md-tabs__list" style="float: right;">
    {% for tab in config.extra.extra_tabs %}
        <li class="md-tabs__item md-extra-tab">
          <a href="{{ tab.url|url }}" class="md-tabs__link">{{ tab.title }}
            {% if tab.icon %}
              &nbsp;{% include tab.icon %}
            {% endif %}
          </a>
        </li>
    {% endfor %}
  </ul>
{% endif %}
````
## What I need
I now want to use the macros plugin and use `include_yaml` to split data from configuration. What I thought would work:

Add the macros plugin and configure it to include an external yaml file and remove the extra_tabs variable under extra in mkdocs.yml
```yaml
plugins:
  - search
  - macros
    include_yaml:
    - assets/data/extra_tabs_data.yml
```
Created a file extra_tabs_data.yml containing the data needed:
```yaml
extra_tabs:
  - title: Link 1
    url: https://example1.com
  - title: Link 2
    url: https://example2.com
    icon: .icons/material/information-slab-box-outline.svg
```
In the tabs.html partial, access the `extra_tabs` variable to generate the menu items

However this did not work, nothing was rendered.

## What I tried

In the tabs.html partial, I used `extra_tabs` , `config.extra.extra_tabs` and some other combinations as variable and removed the if clause.

I used a key: value pair to include the yaml file using `et: assets/data/extra_tabs_data.yml`. During serving, an error was thrown: `jinja2.exceptions.UndefinedError: 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'et'`

## Questions
1. Can overridden partials access the variables from included yaml files by the macros plugin?
2. If so, how can I access these variables meaning what the exact syntax is to acces variables in included yaml files?
I thought I would be able to use the `extra` as stated in https://github.com/fralau/mkdocs_macros_plugin/discussions/181
3. Is there another way using the macros plugin to achieve this?

**Comment by fralau** [comment]
Thanks for your question. I am not sure exactly what issue you are meeting.

Perhaps a formatting issue in the `config.yaml` file? Here is what I see:

```yaml
plugins:
  - search
  - macros
    include_yaml:
    - assets/data/extra_tabs_data.yml
```

The last line looks suspicious to me, because there should be an indentation.

Since I do not see why there should be an `et` attribute in that file, was it unintentional? Would it be worth thoroughly checking the syntax?

**Reply by pvdemael** [reply]
Sorry, was a mistake during formatting of post. There is an indentation.
I got to the `et` as shown below. I defined it as a key-value pair as the documentation of the plugin describes but is does not work
```yaml
plugins:
  - search
  - macros
    include_yaml:
      - et: assets/data/extra_tabs_data.yml
```

When the site is server, I see the following which suggests the file is loaded well.
I defined an attribute `version` under `extra` which is also detected well by the plugin.
```
INFO    -  [macros] - Loading yaml file: C:\...\mkdocs_site\docs/assets/data/extra_tabs_data.yml
INFO    -  [macros] - Extra variables (config file): ['version']
INFO    -  [macros] - Extra filters (module): ['pretty']
```

In tabs.html, I tried to access the attribute as follows
- without key
  ```yaml
  include_yaml:
    - assets/data/extra_tabs_data.yml
  ```

  ` {% for tab in config.extra.extra_tabs %}` or `{% for tab in extra_tabs %}` 

   Page renders without errors but without extra links

- with key
  ```yaml
  include_yaml:
    - et: assets/data/extra_tabs_data.yml
  ```

  ` {% for tab in config.extra.et.extra_tabs %}` or `{% for tab in et.extra_tabs %}` 

  Page not rendered, exits with error

Is there something I am missing? I have doublechecked syntax and it seems to be correct.
