### DISCUSSION TITLE
Strange TOC extension behaviour with macros-generated page content

### DISCUSSION THREAD

**Discussion by Andre601** [fralau/mkdocs-macros-plugin#256] [Q&A]
I have the following template file included on a page to generate content:

<details><summary>Details</summary>
<p>

```markdown
{% if page.meta.constructors %}
## Constructor Details

{% for constructor in page.meta.constructors %}
<div class="api-detail" markdown>

{% set name = namespace(text = constructor.name ~ "(") %}
{% for parameter in constructor.parameters %}
  {% set name.text = name.text ~ parameter.type %}
  {% if loop.revindex > 1 %}{% set name.text = name.text ~ ", " %}{% endif %}
{% endfor %}
{% set name.text = name.text ~ ")" %}

{% if constructor.deprecated %}
  {% set name.text = "<api__deprecated></api__deprecated> " ~ name.text %}
{% endif %}

{% for attribute in constructor.attributes %}
  {% set name.text = "<api__{{- attribute -}}></api__{{- attribute -}}> " ~ name.text %}
{% endfor %}

### {{ name.text | e }} { #{{ name.text | lower() | replace(' ', '-') | e }} }

{% if constructor.deprecated %}
/// deprecated | Deprecation Warning
{{ constructor.deprecated }}
///
{% endif %}

{% if constructor.description %}
<p class="api-detail__description">

{{ constructor.description }}

</p>
{% endif %}

{% if constructor.parameters %}
#### Parameters: { #{{ constructor.name | lower() | replace(' ', '-') | e }}-parameters }

{% for parameter in constructor.parameters %}
- {% for attribute in parameter.attributes %}<api__{{- attribute -}}></api__{{- attribute -}}>{% endfor %} `{{ parameter.type | e}}: {{ parameter.name }}`{% if parameter.description %} - {{ parameter.description }}{% endif %}
{% endfor %}
{% endif %}

</div>
{% endfor %}

{% endif %}
```

</p>
</details> 

What I now noticed is, that the `toc` extension of Python-Markdown has a mental breakdown when generating the link within the "Table of Contents" section.
Either that or the Theme (Material for MkDocs) has a mental breakdown.

I'm unsure of what could be the cause here, but my current guesses go towards the `e` filter within the `{ #{{ name.text | lower() | replace(' ', '-') | e }} }` part as the generated link seems to be similar to URL encoded values.

To give an example, one site has the following page meta set:
```yaml
constructors:
  - name: 'ProfileEntry'
    description: |
      Creates a new instance of a ProfileEntry with the given values.<br>
      It's recommended to use the <a href="./builder/"><code>Builder</code> class</a> for a more convenient configuration of the Settings.
    parameters:
      - name: 'motd'
        description: 'The MOTD to use.'
        type: 'List<String>'
        attributes:
          - notnull
      - name: 'players'
        description: 'The players (Lines) to show in the hover.'
        type: 'List<String>'
        attributes:
          - notnull
      - name: 'playerCountText'
        description: 'The text to display instead of the player count.'
        type: String
        attributes:
          - nullable
      - name: 'favicon'
        description: 'The favicon to use.'
        type: String
        attributes:
          - nullable
      - name: 'hidePlayersEnabled'
        description: 'Whether player count should be hidden.'
        type: NullBool
        attributes:
          - notnull
      - name: 'extraPlayersEnabled'
        description: 'Whether the extra players option should be enabled.'
        type: NullBool
        attributes:
          - notnull
      - name: 'maxPlayersEnabled'
        description: 'Whether the max players option should be enabled.'
        type: NullBool
        attributes:
          - notnull
      - name: 'onlinePlayersCount'
        description: 'The number to set for the Online Players count.'
        type: String
        attributes:
          - nullable
      - name: 'hidePlayersHoverEnabled'
        description: 'Whether the online Players Hover should beenabled.'
        type: NullBool
        attributes:
          - notnull
      - name: 'extraPlayersCount'
        description: 'The number to add to the online Players for the extra Players.'
        type: String
        attributes:
          - nullable
      - name: 'maxPlayersCount'
        description: 'The number to set for the max Players count.'
        type: String
        attributes:
          - nullable
    seealso:
      - name: 'ProfileEntry.Builder'
        link: './builder/'
```

And this is the resulting link within the `toc`:
```
#profileentry(list%02wzxhzdk:4%03string%02wzxhzdk:5%03,-list%02wzxhzdk:6%03string%02wzxhzdk:7%03,-string,-string,-nullbool,-nullbool,-nullbool,-string,-nullbool,-string,-string)
```
...which is completely different from the one generated through the attribute list extension:
```
#profileentry(list<string>,-list<string>,-string,-string,-nullbool,-nullbool,-nullbool,-string,-nullbool,-string,-string)
```

I ask here, as I believe this to be an issue on my end using the Macros plugin.

Here is also my current `plugins` and `markdown_extensions` configurations:

<details><summary>Details</summary>
<p>

```yaml
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.snippets:
      base_path: docs/.snippets
      auto_append:
        - links.md
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.details:
  - pymdownx.caret:
```

</p>
</details>
