### DISCUSSION TITLE
Can I use this with markdownextradata?

### DISCUSSION THREAD

**Discussion by EdwardMoyse** [fralau/mkdocs-macros-plugin#257] [General]
Sorry if this is an obvious question, but I have looked in the docs for a while now

I've been using [markdownextradata](https://github.com/rosscdh/mkdocs-markdownextradata-plugin), and in particular really liked that I could just pick up yaml files from `_data`, rather than making `mkdocs.yaml` huge. However then I found `macros` and it seemed like it could do all that `markdownextradata` could do and more, so I removed that. But it seems like it does not pick up variable definitions from `_data`. Before I re-install `markdownextradata`, can anyone confirm that this won't break anything? Or is there a way to do what I want using this plugin?

**Comment by fralau** [comment]
Thanks for your question. Mkdocs-Macros, by default [reads from the `extra` part of the config file](https://mkdocs-macros-plugin.readthedocs.io/en/latest/#simple-example), as `markdownextradata` -- and indeed that was the inspiration. 

For[ reading external files](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#declaring-external-yaml-files), there is no default directory, but it should be straghtforward to define your `docs/_data` directory as the source.

```yaml
plugins:
    - search
    - macros:
        include_yaml:
          - docs/_data
```
In haven't checked it; let me know how it went (in case of issue, just read the [corresponding part of the documentation](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#declaring-external-yaml-files)).

**Reply by EdwardMoyse** [reply]
Thank very much for your reply, which was very helpful!

This isn't quite as easy as `markdownextra` where I didn't need to specify anything in `mkdocs.yaml` and I could just have:
```
docs/_data
  gitlab_labels.yaml
  locations.yaml         
  site.yaml
```
and then the filename is the first part of the scope (i.e. `{{locations.athena_basics}}` works fine)

But it seems I can recreate this with:
```
plugins:
  - search
  - macros:
      include_yaml:
        - docs/_data/locations.yaml
        - docs/_data/gitlab_labels.yaml
        - docs/_data/site.yaml
```
and then also modifying `locations.yaml` to add the `locations` scope i.e.
```
locations:
  athena_basics: athena/basics
```
(before with `markdownextra`, `locations` was not necessary, but this is a one-time change and so not a big deal).

But I'm now getting this error:
```
_UndefinedError_: 'super_collections.SuperDict object' has no attribute 'data'
```
from `{{site.data.git.branchMainShort}}` when the `sites.yaml` looks like:
```
site:
  data:
    git:
      athena_git_url: https://gitlab.cern.ch/atlas/athena
```

Hopefully I'm not missing anything obvious, but I would have thought this would work.

TBH I could just change this naming, so it's not a disaster, but since I'm migrating a large site from Jekyll (and other people will eventually join the effort), it would make things a little easier if this just worked as-is...
