### DISCUSSION TITLE
Custom name for main.py

### DISCUSSION THREAD

**Discussion by allanleal** [fralau/mkdocs-macros-plugin#62] [Q&A] [answered]
Hi, is it possible to use a custom name for `main.py`? If so, how do I configure this in my `mkdocs.yml` file?

**Comment by fralau** [comment, marked as answer]
Yes!

```yaml
plugins:
  ...
  - macros:
        module_name: source_code
```

See documentation: https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
