### ISSUE TITLE
Variables don't work in overriden templates

### ISSUE THREAD

**Issue by ddorian** [fralau/mkdocs-macros-plugin#200]
Using the simple example https://mkdocs-macros-plugin.readthedocs.io/en/latest/#simple-example

The defined variable in mkdocs.yml:
```yaml
plugins:
  - search
  - macros:
      on_error_fail: true
      on_undefined: strict
extra:
    unit_price: 10
```

Prints black string `` when put as `{{ unit_price }}` in an **overridden template**. 

It works in this format though `{{ config.extra.unit_price }}`.

The problem is that it doesn't cause an error with the configuration above but prints blank string.
