### ISSUE TITLE
Header anchor missing end of comment tag processing content produced with attribute lists

### ISSUE THREAD

**Issue by jodygarnett** [fralau/mkdocs-macros-plugin#208]
I have gotten stuck on an interesting challenge, I am cleaning up some docs converted with pandoc resulting in headers with [attribute_list](https://python-markdown.github.io/extensions/attr_list/) snippets information.

```
## Installing the Db2 extension {#Db2_install}
```

This falls squarely into the [User Manual "Elsewhere" Solution 5](https://mkdocs-macros-plugin.readthedocs.io/en/latest/rendering/#solution-5-altering-the-syntax-of-jinja2-for-mkdocs-macros)

```
plugins:
  - macros:
      render_by_default: false
      on_error_fail: true
      on_undefined: keep
      j2_block_start_string: '[[%'
      j2_block_end_string: '%]]'
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'
```

These settings are picked up:
```
INFO    -  Building documentation...
INFO    -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'render_by_default': False, 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '[[%', 'j2_block_end_string': '%]]', 'j2_variable_start_string': '[[', 'j2_variable_end_string': ']]', 'on_undefined':
           'keep', 'on_error_fail': True, 'verbose': False}
INFO    -  [macros] - Extra variables (config file): ['homepage', 'social', 'version', 'release']
INFO    -  [macros] - Extra filters (module): ['pretty']
INFO    -  [macros] - Found j2 variable 'block_start_string': '[[%'
INFO    -  [macros] - Found j2 variable 'block_end_string': '%]]'
INFO    -  [macros] - Found j2 variable 'variable_start_string': '[['
INFO    -  [macros] - Found j2 variable 'variable_end_string': ']]'
```

But stumble on `{#identifier}`:

````
INFO    -  [macros] - ERROR # _Macro Syntax Error_

           _File_: `data/database/h2.md`

           _Line 7 in Markdown file:_ **Missing end of comment tag**
           ```markdown
           ## Installing the H2 extension {#h2_install}
           ```
````

Is there a need for a `j2_comment_start_string` and `j2_comment_end_string` ?

**Comment by jodygarnett** [comment]
As a workaround I am going to try and post process the content to:
```
## Installing the Db2 extension {: #Db2_install }
```

**Comment by fralau** [comment]
Could be 🤔 

For reference, 

- [definition of the two new arguments in Jina2 doc](https://jinja.palletsprojects.com/en/3.1.x/api/#high-level-api)
- [definition of the two config parameters in the plugin's code](https://github.com/fralau/mkdocs-macros-plugin/blob/7368260754c65b74e582609d4cd7e38d30b05f7b/mkdocs_macros/plugin.py#L81C1-L104C6)
- [the argument should automatically be taken into consideration providing the two new parameters respect the naming convention](https://github.com/fralau/mkdocs-macros-plugin/blob/7368260754c65b74e582609d4cd7e38d30b05f7b/mkdocs_macros/plugin.py#L621C1-L631C50): respectively `j2_comment_start_string` and `j2_comment_end_string`.

Are you willing to propose a PR and test whether it solves the problem for you?

**Comment by jodygarnett** [comment]
My workaround (post processing) was successful ; but I know how frustrating it is if people do not report issues.

----

I am nominally a java developer so I am afraid I am embarrassed to try hacking at Python code.

1. Let me check if Jina2 supports customization of comment start / end string...
2. Checking for code you are following naming convention and adding to "Environment"
3. Looking at Jinja documentation `comment_start_string` and `comment_end_string` are documented as parameters
4. I am not sure how Environment is handed over to Jinja as paramaters but it is worth a test

**Comment by fralau** [comment]
@jodygarnett No problem.  If you prefer, I can do the change and it might still be fun for you to have a look at the diff?

When a didn't know anything at all of Python, I chose a super simple and short manual called [Python Phrasebook](https://www.amazon.com/Python-Phrasebook-Brad-Dayley/dp/0672329107); it was easy reading, and I completed it in a couple of evenings. It gave the few central ideas on which I could build all the rest. You might need a more recent book, because it covers Python 2 (instead of Python 3), but it's the approach that worked for me.

**Comment by fralau** [comment]
I made the update with e.g.:

```yaml
plugins:
  - search
  - macros:
      j2_block_start_string: '[[%'
      j2_block_end_string: '%]]'
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'
      j2_comment_start_string: '[#'
      j2_comment_end_string: '#]'
```

I also updated the `new_syntax` website (in the `test` directory) and checked that it works.

Could you try it for your use case and let me know if it works?
