### ISSUE TITLE
Dealing with newlines in output of macros

### ISSUE THREAD

**Issue by timvink** [fralau/mkdocs-macros-plugin#240]
Consider the following example:

```python
# main.py
def define_env(env):
    """
    This is the hook for the functions (new form)
    """

    @env.macro
    def say_hello():
        return "hello\nthere\nworld!"
``` 

```yaml
# mkdocs.yml
site_name: Example
theme: mkdocs

nav:
    - Home: index.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
``` 

And

```markdown
# Homepage

{{ say_hello() }}

Now inside an admonition

!!! note

    I just want to say:

    {{ say_hello() }}
```

This renders as:

![image](https://github.com/user-attachments/assets/dcb18955-09db-4de7-8d2e-3442fec32696)

Same in `material` theme:

![image](https://github.com/user-attachments/assets/5c264f04-f46b-4887-9fb2-a7a96de263e0)

The reason is that the newlines (`\n`) do not keep the indentation of the first line, so the admonition breaks (the same applies to things like content tabs). I explained that in the table-reader how to page here https://timvink.github.io/mkdocs-table-reader-plugin/howto/use_jinja2/. The solution I use, to add back the idendation to new lines, is hacky.

Ideally, `mkdocs-macros`  would detect if a macros is placed on a page with any indentation, and ensure the same level of indentation is used across all text output. I do the same in `table-reader` when I use regex replacements. 

I am not sure if it is possible though, if jinja is aware of the original indentation. I know you've gone deep into jinja, maybe we can make this work automatically.

Some interesting links:

- jinja `indent` filter block https://stackoverflow.com/questions/21991479/jinja2-correctly-indent-included-block
- jinja whitespace control: https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control
- issue on Preserving whitespace prefix in multiline strings https://github.com/pallets/jinja/issues/178
